### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by waelwalid** [nanuc/laravel-camunda#1]
Is there any available documentation ?

**Comment by wertmenschen** [comment]
Sorry, not really. I use it for some of my Laravel projects where I need Camunda. It's very basic and rudimentary. It's a wrapper around https://docs.camunda.org/manual/7.8/reference/rest/.

If you configure the config file, you should be able to do things like 
```
$processInstance = ProcessDefinition::byKey($processDefinitionKey)->startInstance();
$task = $processInstance->currentTask();
```

Regards
Sebastian

**Comment by waelwalid** [comment]
I'm Using Rest API but i don`t know how to authenticate the user request via REST API and i did't found anything about that then noticed in your config file 2 variables (Camunda user and password) so could you please explain that how to authenticate your connection (API Requests) with camunda .

Thank u :)

**Comment by wertmenschen** [comment]
Just create a user in the Camunda Admin panel and then enter the user credentials into the .env file.

**Comment by vahidalvandi** [comment]
please show a simple project work with this package

thank you

**Comment by SebastianSchoeps** [comment]
As you see, there have been no updates in a long time, so this package is kind of abandoned. But it still stands: add the necessary .env keys, and call the methods like in the comment above.

```
CAMUNDA_API_URL=http://localhost:8080/
CAMUNDA_API_TENANT_ID=sometenant
CAMUNDA_API_USER=demo
CAMUNDA_API_PASSWORD=demo

$processInstance = ProcessDefinition::byKey($processDefinitionKey)->startInstance();
$task = $processInstance->currentTask();
```
